[flake8]
exclude = dydx3/starkex/starkex_resources
per-file-ignores = __init__.py:F401
max-line-length = 100
extend-ignore = F401,F841

[tox]
envlist = py38, py39, py310, py311, py312

[testenv]
commands =
  pytest {posargs: tests}
deps =
  -rrequirements-test.txt
passenv = V3_API_HOST
