name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements-lint.txt -r requirements.txt

      - name: Lint with flake8
        run: flake8

      - name: Type check with mypy
        run: mypy dydx3/ --ignore-missing-imports
